### ISSUE TITLE
FFT version issues

### ISSUE THREAD

**Issue by XiaoHaoPan** [rebeccaeexu/DTNet#1]
Thank you very much for your work, I'm having some problems with your code parts.About this code`DD[:, :, i] = torch.fft.ifft(im[:, :, i], norm='ortho', dim=-1).real`
What version of torch are you using? My version is 1.6 and it doesn't seem to have torch.fft.ifft, I looked up some information and the old version seems to be this code`torch.irfft(output_fft_old , signal_ndim=2, normalized=False, onesided=False)`
However, in the new version, the input data type is complex, and in the old version, it is a two-dimensional vector formed by the real part and the imaginary part, but the Fourier transformation process of the feature in your code does not seem to use`torch.fft.fft`，I'm not quite sure what type of data`im[:, :, i]` is.Do you have a way to invert the`im[:, :, i]`without upgrading the torch version?

**Comment by rebeccaeexu** [comment]
My torch version: 1.10.0+cu111

**Comment by XiaoHaoPan** [comment]
Thank you for your reply
