### ISSUE TITLE
About Demoieing and Alignment

### ISSUE THREAD

**Issue by XiaoHaoPan** [rebeccaeexu/DTNet#2]
Why you put alignment after demoieing？ I've found that there is some instability when using the PCD alignment in the VDmoire paper.Is it based on this aspect of your consideration that you put demoireing before alignment?

**Comment by rebeccaeexu** [comment]
Moire patterns between different frames may have varying positions, colors, and shapes. This variability can pose significant challenges when directly aligning images with moire patterns. Referring to equations 2 and 3 in our paper, it is more appropriate to perform some pre-demoiré processing as a preliminary step.

**Comment by XiaoHaoPan** [comment]
Thank you very much for your answer.
